title: Valetudo
description: >-
  Valetudo aims to be a vendor-agnostic abstraction and cloud replacement for vacuum robots which started as a standalone binary on rooted roborock vacuums.
baseurl: ""
url: https://valetudo.cloud
github_username: Hypfer

plugins:
  - jekyll-seo-tag
collections:
  pages:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
